#!/bin/bash
#
# /usr/local/sbin/ceph-dash
#
# Copyright 2016, Alexander Jackson <alexander.jackson@syncwerk.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Uncomment to run in verbose mode
#set -x


case "$1" in
        start)
            /usr/local/sbin/ceph-dash-bin/ceph-dash.py > /dev/null 2>&1 &
            echo "Ceph dash started"
            ;;

        stop)
            kill $(ps aux | grep /usr/local/sbin/ceph-dash-bin/ceph-dash.py | grep -v grep | awk '{ print $2 }' | xargs) > /dev/null 2>&1
            ;;

        status)
            if kill -0 $(ps aux | grep /usr/local/sbin/ceph-dash-bin/ceph-dash.py | grep -v grep | awk '{ print $2 }' | xargs) > /dev/null 2>&1; then
                echo "Ceph dash is active"
            else
                echo "Ceph dash is inactive"
            fi
            ;;
        restart)
            /usr/local/sbin/ceph-dash stop
            /usr/local/sbin/ceph-dash start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|status}"
            exit 1

esac
