#!/bin/bash
#
# create-seafile-user-preconfiguration-files
#
# Copyright 2016, Alexander Jackson <alexander.jackson@seafile.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Uncomment to run in verbose mode
set -x


# Vars
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PROTO=http
SERVER_ADDRESS=my.seafile.server
ADMIN_TOKEN=my-admin-token
WORK_DIR=${TIMESTAMP}_seafile-user-preconfiguration-files


# Get all users from Seafile server
mkdir -p ./${WORK_DIR}
curl -H "Authorization: Token ${ADMIN_TOKEN}" -H 'Accept: application/json; indent=4' ${PROTO}://${SERVER_ADDRESS}/api2/accounts/?start=-1\&limit=-1 | grep @ | awk '{ print $2 }' | sed 


# Create preconfiguration files
cat ./${WORK_DIR}/userlist.txt | while read line ; do
mkdir -p ./${WORK_DIR}/${line}


## Linux and OSX
cat > ./${WORK_DIR}/${line}/.seafilerc << EOF
[preconfigure]
PreconfigureDirectory = ~/
PreconfigureUsername = ${line}
PreconfigureServerAddr = ${PROTO}://${SERVER_ADDRESS}
PreconfigureServerAddrOnly = 0
HideConfigurationWizard = 0
PreconfigureKeepConfigWhenUninstall = 0
QT_DEVICE_PIXEL_RATIO = auto
EOF


## Windows
cat > ./${WORK_DIR}/${line}/seafile.ini.tmp << EOF
[preconfigure]
PreconfigureDirectory = "%USERPROFILE%"
PreconfigureUsername = ${line}
PreconfigureServerAddr = ${PROTO}://${SERVER_ADDRESS}
PreconfigureServerAddrOnly = 0
HideConfigurationWizard = 0
PreconfigureKeepConfigWhenUninstall = 0
QT_DEVICE_PIXEL_RATIO = auto
EOF

cat > ./${WORK_DIR}/${line}/seafile-client.reg.tmp << EOF
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Seafile]
"PreconfigureServerAddr"="${PROTO}://${SERVER_ADDRESS}"
"PreconfigureUsername"="${line}"
"PreconfigureDirectory"="%USERPROFILE%"
"PreconfigureServerAddrOnly"="1"
"HideConfigurationWizard"="1"
"PreconfigureKeepConfigWhenUninstall"="1"
"QT_DEVICE_PIXEL_RATIO"="auto"

[HKEY_CURRENT_USER\Software\Seafile\Seafile Client]

[HKEY_CURRENT_USER\Software\Seafile\Seafile Client\Behavior]
"hideDockIcon"="false"
"hideMainWindowWhenStarted"="true"
"checkLatestVersion"="true"
EOF


# Convert seafile.ini seafile-client.reg and to Windows line format
for i in seafile.ini seafile-client.reg ; do awk 'sub("$", "\r")' ./${WORK_DIR}/${line}/${i}.tmp > ./${WORK_DIR}/${line}/${i} ; done


# Delete temporary files
for i in seafile.ini seafile-client.reg ; do rm ./${WORK_DIR}/${line}/${i}.tmp ; done

done


# Create ZIP file and clean up
zip ./${WORK_DIR}.zip -r ./${WORK_DIR}
rm -r ./${WORK_DIR}


# Done
cat << EOF

  Done! You will find the pre-configuration files in ./${WORK_DIR}.zip

EOF
